### ISSUE TITLE
Issues with reading in bed files

### ISSUE THREAD

**Issue by maurerv** [CompEpigen/scMethrix#11]
Hi,

If ref_cpgs is not NULL and stranded is FALSE, read_beds expects ref_cpgs to be a data.table. However, the [vignette:88](https://github.com/CompEpigen/scMethrix/blob/c3ccf04c3639163f973f423d89a082d9d4e25e6a/vignettes/x01_load_data.Rmd#L88) suggests using `ref_cpgs = methrix::extract_CPGs`, which would fulfill `(is(ref_cpgs, "list") & all(names(ref_cpgs) == c("cpgs", "contig_lens","release_name"))` (taken
[from](https://github.com/CompEpigen/methrix/blob/master/R/read_bedgraphs.R#L108)). Coming from [methrix](https://github.com/CompEpigen/methrix/tree/4e0464324ec9f3308283e8a6be2345d597eeb756), I did not expect his behavior so it may be beneficial to check the type of ref_cpgs in [read_beds:56](https://github.com/CompEpigen/scMethrix/blob/c3ccf04c3639163f973f423d89a082d9d4e25e6a/R/read_beds.R#L56).

This similarly applies to colData. The [vignette:95](https://github.com/CompEpigen/scMethrix/blob/c3ccf04c3639163f973f423d89a082d9d4e25e6a/vignettes/x01_load_data.Rmd#L95) shows that colData is a data.frame, which matches the check in [read_beds:57](https://github.com/CompEpigen/scMethrix/blob/c3ccf04c3639163f973f423d89a082d9d4e25e6a/R/read_beds.R#L57). However, if colData is not NULL,  [read_beds:148-158](https://github.com/CompEpigen/scMethrix/blob/c3ccf04c3639163f973f423d89a082d9d4e25e6a/R/read_beds.R#L148-L158) expects colData to have a a "Sample" column and the user to submit the reads argument, both are not mentioned in the vignette. To make a long story short, the current implementation will result in a merging error like so: _fix.by(by.x, x) : 'by' must specify a uniquely valid column_.

[read_beds:60](https://github.com/CompEpigen/scMethrix/blob/c3ccf04c3639163f973f423d89a082d9d4e25e6a/R/read_beds.R#L60) :`.validateValue(batch_size,"> 1"," < length(files)")` files will be out of scope once `length(files)` is evaluated. A possible fix would be `.validateValue(batch_size,"> 1"," paste0("<", length(files) ) )`

**Comment by knacko** [comment]
> If ref_cpgs is not NULL and stranded is FALSE, read_beds expects ref_cpgs to be a data.table. However, the vignette:88 suggests using ref_cpgs = methrix::extract_CPGs, which would fulfill (is(ref_cpgs, "list") & all(names(ref_cpgs) == c("cpgs", "contig_lens","release_name")) (taken
from). Coming from methrix, I did not expect his behavior so it may be beneficial to check the type of ref_cpgs in read_beds:56.

The extra list items (chr sizes and genome id) aren't really needed in scMethrix, so I've just added it here without those parts.

> This similarly applies to colData. The vignette:95 shows that colData is a data.frame, which matches the check in read_beds:57. However, if colData is not NULL, read_beds:148-158 expects colData to have a a "Sample" column and the user to submit the reads argument, both are not mentioned in the vignette. To make a long story short, the current implementation will result in a merging error like so: fix.by(by.x, x) : 'by' must specify a uniquely valid column.

I think I originally had it in the H5 and mem read functions, so it's just leftover from that. I've switched it to a function instead and added it back in place.

> read_beds:60 :.validateValue(batch_size,"> 1"," < length(files)") files will be out of scope once length(files) is evaluated. A possible fix would be .validateValue(batch_size,"> 1"," paste0("<", length(files) ) )

Good point! Fixed! I thought it would mess up the style of the error message, but it works totally fine.
